// File: keycodes.rs
// Description: Contains all valid keycodes for cc_engine keyboard firmware
#[repr(u8)]
#[allow(dead_code)]
#[allow(non_camel_case_types)]
#[derive(Copy, Clone, PartialEq)]
pub enum CCKeycode {
    _______ = 0x00,
    ___A___ = 0x04,
    ___B___ = 0x05,
    ___C___ = 0x06,
    ___D___ = 0x07,
    ___E___ = 0x08,
    ___F___ = 0x09,
    ___G___ = 0x0A,
    ___H___ = 0x0B,
    ___I___ = 0x0C,
    ___J___ = 0x0D,
    ___K___ = 0x0E,
    ___L___ = 0x0F,
    ___M___ = 0x10,
    ___N___ = 0x11,
    ___O___ = 0x12,
    ___P___ = 0x13,
    ___Q___ = 0x14,
    ___R___ = 0x15,
    ___S___ = 0x16,
    ___T___ = 0x17,
    ___U___ = 0x18,
    ___V___ = 0x19,
    ___W___ = 0x1A,
    ___X___ = 0x1B,
    ___Y___ = 0x1C,
    ___Z___ = 0x1D,
    ___1___ = 0x1E,
    ___2___ = 0x1F,
    ___3___ = 0x20,
    ___4___ = 0x21,
    ___5___ = 0x22,
    ___6___ = 0x23,
    ___7___ = 0x24,
    ___8___ = 0x25,
    ___9___ = 0x26,
    ___0___ = 0x27,
    _ENTER_ = 0x28,
    __ESC__ = 0x29,
    BACK_SP = 0x2A,
    __TAB__ = 0x2B,

    _SPACE_ = 0x2C,

    SEMICLN = 0x33,
    _QUOTE_ = 0x34,

    _COMMA_ = 0x36,
    __DOT__ = 0x37,
    _SLASH_ = 0x38,

    FUNCT01 = 0x3A,
    FUNCT02 = 0x3B,
    FUNCT03 = 0x3C,
    FUNCT04 = 0x3D,
    FUNCT05 = 0x3E,
    FUNCT06 = 0x3F,
    FUNCT07 = 0x40,
    FUNCT08 = 0x41,
    FUNCT09 = 0x42,
    FUNCT10 = 0x43,
    FUNCT11 = 0x44,
    FUNCT12 = 0x45,

    _PRINT_ = 0x46,
    _SLOCK_ = 0x47,
    _PAUSE_ = 0x48,
    _INSER_ = 0x49,
    __HOME_ = 0x4A,
    PAGE_UP = 0x4B,
    __DEL__ = 0x4C,
    __END__ = 0x4D,
    PAGE_DN = 0x4E,
    _RIGHT_ = 0x4F,
    _LEFT__ = 0x50,
    _DOWN__ = 0x51,
    __UP___ = 0x52,

    L__CTRL = 0xE0,
    L_SHIFT = 0xE1,
    L___ALT = 0xE2,
    L___GUI = 0xE3,

    // custom codes for CC Firmware
    LAYER(u8),          // layer shift key
    PASSTHR,            // pass-through
    MACRO(fn()),        // macro
    MT(CCModifier, u8), // mod tap
}

#[repr(u8)]
#[allow(dead_code)]
#[allow(non_camel_case_types)]
#[derive(Copy, Clone, PartialEq)]
pub enum CCModifier {
    L_CTRL = 0x01,
    L_SHFT = 0x02,
    L_ALT = 0x04,
    L_GUI = 0x08,
    R_CTRL = 0x10,
    R_SHIFT = 0x20,
    R_ALT = 0x40,
    R_GUI = 0x80,
}

impl From<u8> for CCKeycode {
    fn from(value: u8) -> Self {
        match value {
            0x00 => CCKeycode::_______,
            0x04 => CCKeycode::___A___,
            0x05 => CCKeycode::___B___,
            0x06 => CCKeycode::___C___,
            0x07 => CCKeycode::___D___,
            0x08 => CCKeycode::___E___,
            0x09 => CCKeycode::___F___,
            0x0A => CCKeycode::___G___,
            0x0B => CCKeycode::___H___,
            0x0C => CCKeycode::___I___,
            0x0D => CCKeycode::___J___,
            0x0E => CCKeycode::___K___,
            0x0F => CCKeycode::___L___,
            0x10 => CCKeycode::___M___,
            0x11 => CCKeycode::___N___,
            0x12 => CCKeycode::___O___,
            0x13 => CCKeycode::___P___,
            0x14 => CCKeycode::___Q___,
            0x15 => CCKeycode::___R___,
            0x16 => CCKeycode::___S___,
            0x17 => CCKeycode::___T___,
            0x18 => CCKeycode::___U___,
            0x19 => CCKeycode::___V___,
            0x1A => CCKeycode::___W___,
            0x1B => CCKeycode::___X___,
            0x1C => CCKeycode::___Y___,
            0x1D => CCKeycode::___Z___,
            0x1E => CCKeycode::___1___,
            0x1F => CCKeycode::___2___,
            0x20 => CCKeycode::___3___,
            0x21 => CCKeycode::___4___,
            0x22 => CCKeycode::___5___,
            0x23 => CCKeycode::___6___,
            0x24 => CCKeycode::___7___,
            0x25 => CCKeycode::___8___,
            0x26 => CCKeycode::___9___,
            0x27 => CCKeycode::___0___,
            0x28 => CCKeycode::_ENTER_,
            0x29 => CCKeycode::__ESC__,
            0x2A => CCKeycode::BACK_SP,
            0x2B => CCKeycode::__TAB__,

            0x2C => CCKeycode::_SPACE_,

            0x33 => CCKeycode::SEMICLN,
            0x34 => CCKeycode::_QUOTE_,

            0x36 => CCKeycode::_COMMA_,
            0x37 => CCKeycode::__DOT__,
            0x38 => CCKeycode::_SLASH_,

            0x3A => CCKeycode::FUNCT01,
            0x3B => CCKeycode::FUNCT02,
            0x3C => CCKeycode::FUNCT03,
            0x3D => CCKeycode::FUNCT04,
            0x3E => CCKeycode::FUNCT05,
            0x3F => CCKeycode::FUNCT06,
            0x40 => CCKeycode::FUNCT07,
            0x41 => CCKeycode::FUNCT08,
            0x42 => CCKeycode::FUNCT09,
            0x43 => CCKeycode::FUNCT10,
            0x44 => CCKeycode::FUNCT11,
            0x45 => CCKeycode::FUNCT12,
            0x46 => CCKeycode::_PRINT_,
            0x47 => CCKeycode::_SLOCK_,
            0x48 => CCKeycode::_PAUSE_,
            0x49 => CCKeycode::_INSER_,
            0x4A => CCKeycode::__HOME_,
            0x4B => CCKeycode::PAGE_UP,
            0x4C => CCKeycode::__DEL__,
            0x4D => CCKeycode::__END__,
            0x4E => CCKeycode::PAGE_DN,
            0x4F => CCKeycode::_RIGHT_,
            0x50 => CCKeycode::_LEFT__,
            0x51 => CCKeycode::_DOWN__,
            0x52 => CCKeycode::__UP___,

            0xE0 => CCKeycode::L__CTRL,
            0xE1 => CCKeycode::L_SHIFT,
            0xE2 => CCKeycode::L___ALT,
            0xE3 => CCKeycode::L___GUI,

            _ => CCKeycode::_______,
        }
    }
}

impl From<CCKeycode> for u8 {
    fn from(value: CCKeycode) -> Self {
        match value {
            CCKeycode::_______ => 0x00,
            CCKeycode::___A___ => 0x04,
            CCKeycode::___B___ => 0x05,
            CCKeycode::___C___ => 0x06,
            CCKeycode::___D___ => 0x07,
            CCKeycode::___E___ => 0x08,
            CCKeycode::___F___ => 0x09,
            CCKeycode::___G___ => 0x0A,
            CCKeycode::___H___ => 0x0B,
            CCKeycode::___I___ => 0x0C,
            CCKeycode::___J___ => 0x0D,
            CCKeycode::___K___ => 0x0E,
            CCKeycode::___L___ => 0x0F,
            CCKeycode::___M___ => 0x10,
            CCKeycode::___N___ => 0x11,
            CCKeycode::___O___ => 0x12,
            CCKeycode::___P___ => 0x13,
            CCKeycode::___Q___ => 0x14,
            CCKeycode::___R___ => 0x15,
            CCKeycode::___S___ => 0x16,
            CCKeycode::___T___ => 0x17,
            CCKeycode::___U___ => 0x18,
            CCKeycode::___V___ => 0x19,
            CCKeycode::___W___ => 0x1A,
            CCKeycode::___X___ => 0x1B,
            CCKeycode::___Y___ => 0x1C,
            CCKeycode::___Z___ => 0x1D,
            CCKeycode::___1___ => 0x1E,
            CCKeycode::___2___ => 0x1F,
            CCKeycode::___3___ => 0x20,
            CCKeycode::___4___ => 0x21,
            CCKeycode::___5___ => 0x22,
            CCKeycode::___6___ => 0x23,
            CCKeycode::___7___ => 0x24,
            CCKeycode::___8___ => 0x25,
            CCKeycode::___9___ => 0x26,
            CCKeycode::___0___ => 0x27,
            CCKeycode::_ENTER_ => 0x28,
            CCKeycode::__ESC__ => 0x29,
            CCKeycode::BACK_SP => 0x2A,
            CCKeycode::__TAB__ => 0x2B,

            CCKeycode::_SPACE_ => 0x2C,

            CCKeycode::SEMICLN => 0x33,
            CCKeycode::_QUOTE_ => 0x34,

            CCKeycode::_COMMA_ => 0x36,
            CCKeycode::__DOT__ => 0x37,
            CCKeycode::_SLASH_ => 0x38,

            CCKeycode::FUNCT01 => 0x3A,
            CCKeycode::FUNCT02 => 0x3B,
            CCKeycode::FUNCT03 => 0x3C,
            CCKeycode::FUNCT04 => 0x3D,
            CCKeycode::FUNCT05 => 0x3E,
            CCKeycode::FUNCT06 => 0x3F,
            CCKeycode::FUNCT07 => 0x40,
            CCKeycode::FUNCT08 => 0x41,
            CCKeycode::FUNCT09 => 0x42,
            CCKeycode::FUNCT10 => 0x43,
            CCKeycode::FUNCT11 => 0x44,
            CCKeycode::FUNCT12 => 0x45,

            // add other stuff here
            CCKeycode::_PRINT_ => 0x46,
            CCKeycode::_SLOCK_ => 0x47,
            CCKeycode::_PAUSE_ => 0x48,
            CCKeycode::_INSER_ => 0x49,
            CCKeycode::__HOME_ => 0x4A,
            CCKeycode::PAGE_UP => 0x4B,
            CCKeycode::__DEL__ => 0x4C,
            CCKeycode::__END__ => 0x4D,
            CCKeycode::PAGE_DN => 0x4E,
            CCKeycode::_RIGHT_ => 0x4F,
            CCKeycode::_LEFT__ => 0x50,
            CCKeycode::_DOWN__ => 0x51,
            CCKeycode::__UP___ => 0x52,

            CCKeycode::L__CTRL => 0xE0,
            CCKeycode::L_SHIFT => 0xE1,
            CCKeycode::L___ALT => 0xE2,
            CCKeycode::L___GUI => 0xE3,

            _ => 0x00, // default to no key
        }
    }
}

impl From<char> for CCKeycode {
    fn from(value: char) -> Self {
        match value {
            'a' => CCKeycode::___A___,
            'A' => CCKeycode::___A___,
            'b' => CCKeycode::___B___,
            'B' => CCKeycode::___B___,
            'c' => CCKeycode::___C___,
            'C' => CCKeycode::___C___,
            'd' => CCKeycode::___D___,
            'D' => CCKeycode::___D___,
            'e' => CCKeycode::___E___,
            'E' => CCKeycode::___E___,
            'f' => CCKeycode::___F___,
            'F' => CCKeycode::___F___,
            'g' => CCKeycode::___G___,
            'G' => CCKeycode::___G___,
            'h' => CCKeycode::___H___,
            'H' => CCKeycode::___H___,
            'i' => CCKeycode::___I___,
            'I' => CCKeycode::___I___,
            'j' => CCKeycode::___J___,
            'J' => CCKeycode::___J___,
            'k' => CCKeycode::___K___,
            'K' => CCKeycode::___K___,
            'l' => CCKeycode::___L___,
            'L' => CCKeycode::___L___,
            'm' => CCKeycode::___M___,
            'M' => CCKeycode::___M___,
            'n' => CCKeycode::___N___,
            'N' => CCKeycode::___N___,
            'o' => CCKeycode::___O___,
            'O' => CCKeycode::___O___,
            'p' => CCKeycode::___P___,
            'P' => CCKeycode::___P___,
            'q' => CCKeycode::___Q___,
            'Q' => CCKeycode::___Q___,
            'r' => CCKeycode::___R___,
            'R' => CCKeycode::___R___,
            's' => CCKeycode::___S___,
            'S' => CCKeycode::___S___,
            't' => CCKeycode::___T___,
            'T' => CCKeycode::___T___,
            'u' => CCKeycode::___U___,
            'U' => CCKeycode::___U___,
            'v' => CCKeycode::___V___,
            'V' => CCKeycode::___V___,
            'w' => CCKeycode::___W___,
            'W' => CCKeycode::___W___,
            'x' => CCKeycode::___X___,
            'X' => CCKeycode::___X___,
            'y' => CCKeycode::___Y___,
            'Y' => CCKeycode::___Y___,
            'z' => CCKeycode::___Z___,
            'Z' => CCKeycode::___Z___,
            '0' => CCKeycode::___0___,
            '1' => CCKeycode::___1___,
            '2' => CCKeycode::___2___,
            '3' => CCKeycode::___3___,
            '4' => CCKeycode::___4___,
            '5' => CCKeycode::___5___,
            '6' => CCKeycode::___6___,
            '7' => CCKeycode::___7___,
            '8' => CCKeycode::___8___,
            '9' => CCKeycode::___9___,
            ' ' => CCKeycode::_SPACE_,
            _ => CCKeycode::__ESC__,
        }
    }
}
