// File: keycodes.rs
// Description: Contains all valid keycodes for cc_engine keyboard firmware
#[repr(u8)]
#[allow(dead_code)]
#[allow(non_camel_case_types)]
#[derive(Copy, Clone, PartialEq)]
pub enum CCKeycode {
    CC____A = 0x04,
    CC____B = 0x05,
    CC____C = 0x06,
    CC____D = 0x07,
    CC____E = 0x08,
    CC____F = 0x09,
    CC____G = 0x0A,
    CC____H = 0x0B,
    CC____I = 0x0C,
    CC____J = 0x0D,
    CC____K = 0x0E,
    CC____L = 0x0F,
    CC____M = 0x10,
    CC____N = 0x11,
    CC____O = 0x12,
    CC____P = 0x13,
    CC____Q = 0x14,
    CC____R = 0x15,
    CC____S = 0x16,
    CC____T = 0x17,
    CC____U = 0x18,
    CC____V = 0x19,
    CC____W = 0x1A,
    CC____X = 0x1B,
    CC____Y = 0x1C,
    CC____Z = 0x1D,
    CC____1 = 0x1E,
    CC____2 = 0x1F,
    CC____3 = 0x20,
    CC____4 = 0x21,
    CC____5 = 0x22,
    CC____6 = 0x23,
    CC____7 = 0x24,
    CC____8 = 0x25,
    CC____9 = 0x26,
    CC____0 = 0x27,
    CC__RET = 0x28,
    CC__ESC = 0x29,
    CC_BKSP = 0x2A,
    CC__TAB = 0x2B,

    CC_SPAC = 0x2C,

    CC_SCLN = 0x33,
    CC_QUOT = 0x34,

    CC_COMA = 0x36,
    CC__PER = 0x37,
    CC_SLSH = 0x38,

    CC_FN01 = 0x3A,
    CC_FN02 = 0x3B,
    CC_FN03 = 0x3C,
    CC_FN04 = 0x3D,
    CC_FN05 = 0x3E,
    CC_FN06 = 0x3F,
    CC_FN07 = 0x40,
    CC_FN08 = 0x41,
    CC_FN09 = 0x42,
    CC_FN10 = 0x43,
    CC_FN11 = 0x44,
    CC_FN12 = 0x45,

    CC_RGTA = 0x4F,
    CC_LFTA = 0x50,
    CC_DWNA = 0x51,
    CC__UPA = 0x52,

    CC_CTRL = 0xE0,
    CC_SHFT = 0xE1,
    CC__ALT = 0xE2,
    CC__GUI = 0xE3,

    // custom codes for CC Firmware
    CC_NONE,
    CC_LAY(usize), // layer shift key
    CC_PASS,
}

impl From<u8> for CCKeycode {
    fn from(value: u8) -> Self {
        match value {
            0x04 => CCKeycode::CC____A,
            0x05 => CCKeycode::CC____B,
            0x06 => CCKeycode::CC____C,
            0x07 => CCKeycode::CC____D,
            0x08 => CCKeycode::CC____E,
            0x09 => CCKeycode::CC____F,
            0x0A => CCKeycode::CC____G,
            0x0B => CCKeycode::CC____H,
            0x0C => CCKeycode::CC____I,
            0x0D => CCKeycode::CC____J,
            0x0E => CCKeycode::CC____K,
            0x0F => CCKeycode::CC____L,
            0x10 => CCKeycode::CC____M,
            0x11 => CCKeycode::CC____N,
            0x12 => CCKeycode::CC____O,
            0x13 => CCKeycode::CC____P,
            0x14 => CCKeycode::CC____Q,
            0x15 => CCKeycode::CC____R,
            0x16 => CCKeycode::CC____S,
            0x17 => CCKeycode::CC____T,
            0x18 => CCKeycode::CC____U,
            0x19 => CCKeycode::CC____V,
            0x1A => CCKeycode::CC____W,
            0x1B => CCKeycode::CC____X,
            0x1C => CCKeycode::CC____Y,
            0x1D => CCKeycode::CC____Z,
            0x1E => CCKeycode::CC____1,
            0x1F => CCKeycode::CC____2,
            0x20 => CCKeycode::CC____3,
            0x21 => CCKeycode::CC____4,
            0x22 => CCKeycode::CC____5,
            0x23 => CCKeycode::CC____6,
            0x24 => CCKeycode::CC____7,
            0x25 => CCKeycode::CC____8,
            0x26 => CCKeycode::CC____9,
            0x27 => CCKeycode::CC____0,
            0x28 => CCKeycode::CC__RET,
            0x29 => CCKeycode::CC__ESC,
            0x2A => CCKeycode::CC_BKSP,
            0x2B => CCKeycode::CC__TAB,

            0x2C => CCKeycode::CC_SPAC,

            0x33 => CCKeycode::CC_SCLN,
            0x34 => CCKeycode::CC_QUOT,

            0x36 => CCKeycode::CC_COMA,
            0x37 => CCKeycode::CC__PER,
            0x38 => CCKeycode::CC_SLSH,

            0x3A => CCKeycode::CC_FN01,
            0x3B => CCKeycode::CC_FN02,
            0x3C => CCKeycode::CC_FN03,
            0x3D => CCKeycode::CC_FN04,
            0x3E => CCKeycode::CC_FN05,
            0x3F => CCKeycode::CC_FN06,
            0x40 => CCKeycode::CC_FN07,
            0x41 => CCKeycode::CC_FN08,
            0x42 => CCKeycode::CC_FN09,
            0x43 => CCKeycode::CC_FN10,
            0x44 => CCKeycode::CC_FN11,
            0x45 => CCKeycode::CC_FN12,

            0x4F => CCKeycode::CC_RGTA,
            0x50 => CCKeycode::CC_LFTA,
            0x51 => CCKeycode::CC_DWNA,
            0x52 => CCKeycode::CC__UPA,

            0xE0 => CCKeycode::CC_CTRL,
            0xE1 => CCKeycode::CC_SHFT,
            0xE2 => CCKeycode::CC__ALT,
            0xE3 => CCKeycode::CC__GUI,

            _ => CCKeycode::CC_NONE,
        }
    }
}

impl From<CCKeycode> for u8 {
    fn from(value: CCKeycode) -> Self {
        match value {
            CCKeycode::CC____A => 0x04,
            CCKeycode::CC____B => 0x05,
            CCKeycode::CC____C => 0x06,
            CCKeycode::CC____D => 0x07,
            CCKeycode::CC____E => 0x08,
            CCKeycode::CC____F => 0x09,
            CCKeycode::CC____G => 0x0A,
            CCKeycode::CC____H => 0x0B,
            CCKeycode::CC____I => 0x0C,
            CCKeycode::CC____J => 0x0D,
            CCKeycode::CC____K => 0x0E,
            CCKeycode::CC____L => 0x0F,
            CCKeycode::CC____M => 0x10,
            CCKeycode::CC____N => 0x11,
            CCKeycode::CC____O => 0x12,
            CCKeycode::CC____P => 0x13,
            CCKeycode::CC____Q => 0x14,
            CCKeycode::CC____R => 0x15,
            CCKeycode::CC____S => 0x16,
            CCKeycode::CC____T => 0x17,
            CCKeycode::CC____U => 0x18,
            CCKeycode::CC____V => 0x19,
            CCKeycode::CC____W => 0x1A,
            CCKeycode::CC____X => 0x1B,
            CCKeycode::CC____Y => 0x1C,
            CCKeycode::CC____Z => 0x1D,
            CCKeycode::CC____1 => 0x1E,
            CCKeycode::CC____2 => 0x1F,
            CCKeycode::CC____3 => 0x20,
            CCKeycode::CC____4 => 0x21,
            CCKeycode::CC____5 => 0x22,
            CCKeycode::CC____6 => 0x23,
            CCKeycode::CC____7 => 0x24,
            CCKeycode::CC____8 => 0x25,
            CCKeycode::CC____9 => 0x26,
            CCKeycode::CC____0 => 0x27,
            CCKeycode::CC__RET => 0x28,
            CCKeycode::CC__ESC => 0x29,
            CCKeycode::CC_BKSP => 0x2A,
            CCKeycode::CC__TAB => 0x2B,

            CCKeycode::CC_SPAC => 0x2C,

            CCKeycode::CC_SCLN => 0x33,
            CCKeycode::CC_QUOT => 0x34,

            CCKeycode::CC_COMA => 0x36,
            CCKeycode::CC__PER => 0x37,
            CCKeycode::CC_SLSH => 0x38,

            CCKeycode::CC_FN01 => 0x3A,
            CCKeycode::CC_FN02 => 0x3B,
            CCKeycode::CC_FN03 => 0x3C,
            CCKeycode::CC_FN04 => 0x3D,
            CCKeycode::CC_FN05 => 0x3E,
            CCKeycode::CC_FN06 => 0x3F,
            CCKeycode::CC_FN07 => 0x40,
            CCKeycode::CC_FN08 => 0x41,
            CCKeycode::CC_FN09 => 0x42,
            CCKeycode::CC_FN10 => 0x43,
            CCKeycode::CC_FN11 => 0x44,
            CCKeycode::CC_FN12 => 0x45,

            CCKeycode::CC_RGTA => 0x4F,
            CCKeycode::CC_LFTA => 0x50,
            CCKeycode::CC_DWNA => 0x51,
            CCKeycode::CC__UPA => 0x52,

            CCKeycode::CC_CTRL => 0xE0,
            CCKeycode::CC_SHFT => 0xE1,
            CCKeycode::CC__ALT => 0xE2,
            CCKeycode::CC__GUI => 0xE3,

            _ => 0x04, // default to A I guess?
        }
    }
}
